<?php

namespace AppBundle\Repository;

/**
 * CommandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandRepository extends \Doctrine\ORM\EntityRepository
{
    public function insert(Command $command)
    {
        $this->_em->persist($command);
    }

//    public function findVisitorsFromDate($dateVisit)
//    {
//        $qb = $this->createQueryBuilder('c');
//
//        $qb->where('c.dateVisit = :dateVisit')
//            ->setParameter('dateVisit', $dateVisit);
//
//        return $qb
//            ->getQuery()
//            ->getResult();
//    }

    public function findCommandsWithItsVisitors($dateVisit)
    {
        $qb = $this->createQueryBuilder('c');

        $qb->where('c.dateVisit = :dateVisit')
            ->setParameter('dateVisit', $dateVisit);
        $qb->leftJoin('c.visitors', 'visitors')
            ->addSelect('visitors');

        return $qb
            ->getQuery()
            ->getResult();
    }
}
