<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Command;

/**
 * CommandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandRepository extends \Doctrine\ORM\EntityRepository implements CommandGateway
{
    public function insert(Command $command)
    {
        $this->_em->persist($command);
        $this->_em->flush();
    }



    public function countReservationAt($dateVisit)
    {
        $qb = $this->createQueryBuilder('c');

        $qb ->select('count(v.id)')
            ->where('c.dateVisit = :dateVisit')
            ->setParameter('dateVisit', $dateVisit);
        $qb->leftJoin('c.visitors', 'v');


        return $qb
            ->getQuery()
            ->getSingleScalarResult();
    }
}
