<?php

namespace AppBundle\Repository;

/**
 * visitorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class visitorRepository extends \Doctrine\ORM\EntityRepository
{
}
